### PR TITLE
Added timestamp serialization (uint64_t <-> std::chrono::timepoint)

### PR DESCRIPTION
**Pull request by talhasaruhan**
Only compiled if JS_STD_TIMEPOINT is defined.

### CODE REVIEW

**Comment by talhasaruhan** [comment]
On a second look, it requires std::enable_if and if constexpr, so the proper compiler checks might be needed before enabling this feature, depending on the intended target of the library.

**Comment by jorgen** [comment]
I think its ok if the user enables the define JS_STD_TIMEPOINT that it requires extra functionality. However, can you please add a unit test?

**Comment by talhasaruhan** [comment]
Added the tests.

**Comment by jorgen** [comment]
Awesome, I can fix the ci later today

**Comment by talhasaruhan** [comment]
Cool 👍

**Pull request merged**
