### PR TITLE
Enabling conditional template specialization of TypeHandler<>

### PR DESCRIPTION
**Pull request by talhasaruhan**
Added a second, dummy template parameter to TypeHandler to enable use of std::enable_if and contidional specializations

### CODE REVIEW

**Review by jorgen — COMMENTED** [review]
Will this not break all typehandlers? What improvement can we have? That if some typetrait is available then just one typehandler instead of one pr type?

**Comment by jorgen** [comment]
Do you know if this will effect compile time?

**Comment by jorgen** [comment]
Looks good on the ci👍

**Comment by talhasaruhan** [comment]
> Do you know if this will effect compile time?

No it will not. Because for every instantiation that existed before there will still be one (Enable = void, default parameter).

**Comment by jorgen** [comment]
Thank you for your contribution. My initial reaction was that this was unnecessary, but thinking about it it makes sense.

**Comment by talhasaruhan** [comment]
> Thank you for your contribution. My initial reaction was that this was unnecessary, but thinking about it it makes sense.

Actually I'd needed it for this: #37. I opened a new pull request for that one now.

**Pull request merged**
